/* GENERAL IMAGES */
export const PREGNANTIMAGE = require('./files/mulher_gestante.png')
export const LOGOIMAGE = require('./files/logo_gestar_saude.png')
export const BACKGROUNDPREGNANTIMAGE = require('./files/fundo_mulher_gestante.png')
export const BACKGROUNDPREGNANTIMAGESEMFUNDO = require('./files/fundo_mulher_gestante_sem_logo.png')
export const MAPAPIAUI = require('./files/regioes1.png')
export const ICONPLUS = require('./files/icons/icon_plus.png')
export const ICONBOY = require('./files/icons/icon_boy.png')
export const ICONGIRL = require('./files/icons/icon_girl.png')
export const ICONHEARTRISCO = require('./files/icons/icon_heart_risco.png')
export const ICONHEARTSAUDAVEL = require('./files/icons/icon_heart_saudavel.png')
export const ICONCALENDAR = require('./files/icons/icon_calendario.png')
export const ICONCHECKED = require('./files/icons/icon_checked.png')
export const ICONUP = require('./files/icons/icon_up.png')
export const ICONDOWN = require('./files/icons/icon_down.png')
export const NEXT = require('./files/icons/icon_next.png')
export const PREVIOUS = require('./files/icons/icon_previous.png')
export const ICONCLOSE = require('./files/icons/icon_close_grey.png')