/* GENERAL IMAGES */
export const PREGNANTIMAGE = require('./files/mulher_gestante.png')
export const LOGOIMAGE = require('./files/logo_gestar_saude.png')
export const BACKGROUNDPREGNANTIMAGE = require('./files/fundo_mulher_gestante.png')
export const BACKGROUNDPREGNANTIMAGESEMFUNDO = require('./files/fundo_mulher_gestante_sem_logo.png')
export const MAPAPIAUI = require('./files/regioes1.png')
export const ICONPLUS = require('./files/icons/icon_plus.png')
export const ICONBOY = require('./files/icons/icon_boy.png')
export const ICONGIRL = require('./files/icons/icon_girl.png')
export const ICONHEARTRISCO = require('./files/icons/icon_heart_risco.png')
export const ICONHEARTSAUDAVEL = require('./files/icons/icon_heart_saudavel.png')
export const ICONCALENDAR = require('./files/icons/icon_calendario.png')
export const ICONCHECKED = require('./files/icons/icon_checked.png')
export const ICONUP = require('./files/icons/icon_up.png')
export const ICONDOWN = require('./files/icons/icon_down.png')
export const NEXT = require('./files/icons/icon_next.png')
export const PREVIOUS = require('./files/icons/icon_previous.png')
export const ICONCLOSE = require('./files/icons/icon_close_grey.png')
export const ICONTARGET = require('./files/icons/icon_target.png')

/* REGIOES IMAGES */
export const ICONALTOPARNAIBA = require('./files/icons/regioes/alto_parnaiba.png')
export const ICONCANINDE = require('./files/icons/regioes/caninde.png')
export const ICONCAPIVARA = require('./files/icons/regioes/capivara.png')
export const ICONCARNAUBAIS = require('./files/icons/regioes/carnaubais.png')
export const ICONCOCAIS = require('./files/icons/regioes/cocais.png')
export const ICONENTRERIOS = require('./files/icons/regioes/entre_rios.png')
export const ICONGUARIBAS = require('./files/icons/regioes/guaribas.png')
export const ICONITAUEIRAS = require('./files/icons/regioes/itaueiras.png')
export const ICONLITORAL = require('./files/icons/regioes/litoral.png')
export const ICONMANGABEIRAS = require('./files/icons/regioes/mangabeiras.png')
export const ICONSAMBITO = require('./files/icons/regioes/sambito.png')
